version: '3.8'

services:

  flower:
    image: mher/flower
    ports:
      - "5555:5555"
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672  # Flower UI
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "15672:15672"  # RabbitMQ management UI
      - "5672:5672"    # RabbitMQ default port
  redis:
    image: redis:7.0.11-alpine

  django:
    container_name: django
    build:
      context: ./dcelery
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./dcelery:/usr/src/app/
    ports:
      - 8001:8000
    environment:
      - DEBUG=1
      - SECRET_KEY=0930jd30j9jd09j09j109fj01j9f
      - ALLOWED_HOSTS=localhost,127.0.0.1
    depends_on:
      - redis
  
  celery1:
    container_name: celery1
    build:
      context: ./dcelery
    command: celery --app=dcelery worker --hostname=celeryWorker@&h -l INFO -Q tasks
    volumes:
      - ./dcelery:/usr/src/app/
    environment:
      - DEBUG=1
      - SECRET_KEY=0930jd30j9jd09j09j109fj01j9f
      - ALLOWED_HOSTS=localhost,127.0.0.1
    depends_on:
      - redis
      - django
      - rabbitmq

  celery2:
    container_name: celery2
    build:
      context: ./celeryworker
      dockerfile: Dockerfile
    command: celery -A celerytask worker -l INFO -Q celery,celery:1,celery:2,celery:3,celery:4,celery:5
    volumes:
      - ./celeryworker:/usr/src/app/
    environment:
      - DEBUG=1
      - SECRET_KEY=0930jd30j9jd09j09j109fj01j9f
      - ALLOWED_HOSTS=localhost,127.0.0.1
    depends_on:
      - redis
      - django

    